Замена сообщения при ошибке 415
profcomff/print-bot pull request #41
Opened 2024-04-12 17:35 UTC by iskomir

2024-04-12 18:05 UTC, grigoriev-semyon requested changes

2024-04-12 18:05 UTC, grigoriev-semyon commented on src/handlers.py
> +        vk.send(user, ans.warn_only_pdfs)
Эта ошибка кидается не только в случае не пдф
Еще и в случаях битых пдф
Надо это как то описать 
Мб добавить новое описание просто
И посмотреть используется ли где то то которое ты использовал

2024-04-13 09:48 UTC, annndruha commented on src/handlers.py
> +        vk.send(user, ans.warn_only_pdfs)
Да, здесь лучше добавить новое, более точное описание в answers

2024-04-13 09:50 UTC, annndruha commented
Вообще лучше бы этот PR закрыть и сделать новый с названием ветки на английском. Гит конечно штука +- стабильная, но названия веток на русском могут привести к неудобствам и проблемам

2024-04-19 16:26 UTC, closed without merging