Replacing an error message 415
profcomff/print-bot pull request #42
Opened 2024-04-19 16:39 UTC by iskomir

2024-04-19 17:08 UTC, grigoriev-semyon commented on src/answers.py
> +    warn_didntread_file = '⚠️ Я не смог прочитать файл. Проверьте его целостность или формат, я работаю только с pdf.'
Проверьте его целостность __и__ формат

2024-04-19 17:09 UTC, grigoriev-semyon commented on src/answers.py
> +    warn_didntread_file = '⚠️ Я не смог прочитать файл. Проверьте его целостность или формат, я работаю только с pdf.'
переменную назови `warn_unreadable_file`

2024-04-19 17:09 UTC, grigoriev-semyon requested changes
оставил пару комментов

2024-04-19 17:17 UTC, annndruha commented
Если что, линтер (штука для проверки формата кода) ругается на порядок импортов. Ты можешь посмотреть это во вкладке Actions, или под Блоком "All checks have failed" в details.

Запусти локально в корне репозитория `isort .`, предварительно установив его через `pip install isort` и закоммить изменённый порядок импортов.

2024-04-19 17:22 UTC, annndruha requested changes

2024-04-19 17:22 UTC, annndruha commented on src/handlers.py
> -        vk.send(user, ans.warn_only_pdfs)
Откати эту строку обратно, потому что выше идёт проверка на тип файла и юзеру должно прийти сообщение что формат не тот. Тут ничего менять не нужно.

2024-04-19 17:22 UTC, annndruha commented on src/handlers.py
> -        vk.send(user, ans.warn_only_pdfs)
Откати эту строку обратно, потому что выше идёт проверка на тип файла и юзеру должно прийти сообщение что формат не тот. Тут ничего менять не нужно.

2024-04-19 17:22 UTC, annndruha commented on src/handlers.py
> +        )
Тут норм вроде

2024-04-19 17:24 UTC, annndruha commented on src/answers.py
> -    warn_only_pdfs = '⚠️ Я умею печатать только документы в формате pdf.'
И тут тоже, добавленную строку оставь, а удалённую верни обратно. Твоя новая строка будет использовать только в одном месте -- когда r.status_code == 415

2024-04-19 20:22 UTC, grigoriev-semyon approved these changes
С моей стороны все ок, подождем аппрува @annndruha

2024-04-19 20:23 UTC, grigoriev-semyon commented
+ надо починить пайлайн все таки постараться
зайди в миграции в конфликтный файл и удали newline после коммента многострочного и до импортов

2024-04-20 12:07 UTC, annndruha approved these changes
Норм

2024-04-20 15:13 UTC, merged